### PR TITLE
Add copy-tested-package command

### LINKED ISSUE #193: Testing a dependency within CI
I'm trying to set up testing for a dependency (see https://github.com/sublimelsp/lsp_utils/pull/70) within a Github Actions.

There are some problems with that.

By default the CI script bootstraps Package Control with `ignore_vcs_packages` set to `true`. Having that option enabled with a cloned dependency in Packages results in PC showing an error dialog:

Screenshot 2021-06-19 at 21 43 57

and UnitTesting script failing the `install_package_control` step with:

```
Skipping git package lsp_utils since the setting "ignore_vcs_packages" is set to true
missing dependencies:
lsp_utils
Timeout: Fail to install Package Control.
Error: Process completed with exit code 1.
```
source: https://github.com/sublimelsp/lsp_utils/runs/2865424911

With `ignore_vcs_packages` set to `false` it also errors out with:

```
Error executing: /usr/bin/git symbolic-ref -q HEAD
Working directory: /github/home/.config/sublime-text/Packages/lsp_utils
VCS-based packages can be ignored by changing the "ignore_vcs_packages" setting to true.
Sublime Text will need to be restarted once the setting is changed.
missing dependencies:
lsp_utils
Timeout: Fail to install Package Control.
Error: Process completed with exit code 1.
```
source: https://github.com/sublimelsp/lsp_utils/runs/2865746622

I'm looking for some ideas on how to handle this.

### PR DESCRIPTION
**Pull request by rchl**
Fixes #193

Not finished with it yet. Gonna update the powershell script tomorrow.

Also, should the command be called `copy_package` or `copy_tested_package` or something else?

### CODE REVIEW

**Comment by rchl** [comment]
Actually I would also need something for deleting the package directory as I need to remove what PC installed before using `copy_tested_package`...

Or could make the `CopyTestedPackage` remove the target itself if it exists.

**Comment by rchl** [comment]
Added a `OverwriteExisting` argument to `copy_tested_package`.

Not a fan of boolean parameters like that but didn't have any better idea.

Let me know if the current solution is fine for you. Then I'll update powershell script.

**Comment by rchl** [comment]
ping. Does it look OK?

**Comment by randy3k** [comment]
LGTM. I guess we guess not waste the time to update the powerscripts as I have a plan to replace them with python scripts (unless you want to update them and use  them in lsp-util).

**Comment by rchl** [comment]
Thanks!

I'm fine with not having PowerShell scripts. At least currently since we haven't figured out the Windows testing situation yet.

**Pull request merged**
