### PR TITLE
refactor ci.ps1

### PR DESCRIPTION
**Pull request by guillermooo**
- Refactor script
- Add help so that `help ./ci.ps1` shows it

@randy3k This is ready to merge now.

Thanks!

### CODE REVIEW

**Comment by randy3k** [comment]
You are changing the command names from snake case to camel case. I personally actually prefer snake case plus the travis script also uses snake case. If you really prefer camel case, I don't mind adding some alises. However, I suggest that we do not deprecate the snake case commands (at least for this moment)

**Comment by guillermooo** [comment]
>You are changing the command names from snake case to camel case.

I don't think PS uses underscores to separate words, so it looked wrong to me. I don't mind changing it back.

**Comment by randy3k** [comment]
It seems that the circieci linux build fails randomly. I have seen the random failures several times.

**Comment by randy3k** [comment]
@guillermooo If you really want the camel cases, you could make alias command.

By the way, you might want to push to SublimeText directly next time, so I could test the PR against a sublime package with the environmental variable `UNITTESTING_TAG` to specify the version of UnitTesting.

**Comment by randy3k** [comment]
I would merge it later today if you are not adding the camel case aliases.

**Comment by guillermooo** [comment]
@randy3k Alias are not worth the trouble at this time. I do think camelcase is more PowerShell-y, but not a big deal. Maybe later. There are other things I want to work on before that.

**Pull request merged**
