### PR TITLE
Expose install_package CI command for installing arbitrary packages

### PR DESCRIPTION
**Pull request by rchl**
I must say it's completely untested but it seems like it should work.

### CODE REVIEW

**Comment by randy3k** [comment]
Thank you but you didn't modify the corresponding powershell variant. 

With that said, I am thinking to deprecate all the powershell scripts and use bash/python scripts for all platforms. It should make maintainance a bit easier.

**Comment by rchl** [comment]
I can't find `ci.ps1` file in the repo. But then I have zero knowledge about powershell scripts so not sure how hard it would be to handle.

**Comment by randy3k** [comment]
It's here https://github.com/SublimeText/UnitTesting/tree/master/sbin/ps

It was written by @guillermooo so it's in a very different style. 

Anyway, at some point I am going to remove it.

**Comment by rchl** [comment]
I don't know anything about powersheel but did my best guess at how it should be done.

**Comment by randy3k** [comment]
Thanks.

**Comment by rchl** [comment]
Thanks to you.

BTW. Beautiful history:

Screenshot 2021-06-19 at 23 14 53

Would recommend squash option for my changes at least ;)

**Pull request merged**
