### PR TITLE
refactor run_tests.py

### PR DESCRIPTION
**Pull request by guillermooo**
Cleaning up `run_tests.py`.

### CODE REVIEW

**Comment by guillermooo** [comment]
@randy3k Any idea why this PR might be failing on Linux and macOS but not Windows? Sublime Text always times out on the former platforms.

**Comment by randy3k** [comment]
May you rebase to the current master and use also the circleci? It has an ssh option for debugging

**Comment by randy3k** [comment]
@guillermooo I have fixed the bug at https://github.com/SublimeText/UnitTesting/pull/75/commits/40c7b878d8968857c27e71ee22d5f8f87bf28ad7, it was because a variable was misnamed. However, it seems that there is another bug regrading `check_is_done`: it fails to detect that the tests have been completed.

**Comment by guillermooo** [comment]
@randy3k Thanks for that! I'll take a closer look. In the meantime, I've rebased and lost your edit, so I'll reinstate it.

**Comment by guillermooo** [comment]
@randy3k It seems that Travis-CI will fail if the `flake8` command in the build system returns a non-zero exit code. This does not seem to be the case for Circle-CI or Appveyor. I find this a bit confusing---a build may fail or pass depending on the CI service used. I haven't looked any further into this, however. This is just FYI.

**Comment by guillermooo** [comment]
@randy3k I'm done for now. The Travis CI fail seems to be a glitch, so I think this is ready.

**Comment by randy3k** [comment]
thanks.

**Pull request merged**
