### PR TITLE
Just syntax highlighting

### PR DESCRIPTION
**Pull request by kaste**
This PR just picks the syntax highlighting from PR #82 bc it is easy to decide on and nice to have. Note that I had to patch it (second commit) to make it work.

### CODE REVIEW

**Comment by kaste** [comment]
(Tests are failing on master already, at least on my machine.)

**Comment by kaste** [comment]
Hm, now we're green at least

**Comment by randy3k** [comment]
Thanks, it looks good.

**Comment by jgirardet** [comment]
great idea

**Pull request merged**
