### PR TITLE
Refactor/appveyorscript2

### PR DESCRIPTION
**Pull request by guillermooo**
This branch is ready for merging.

See below for details.

### CODE REVIEW

**Comment by guillermooo** [comment]
Main differences to #106:

`appveyor.ps1` is still downloaded to the current directory, but helper scripts get downloaded to `$env:TEMP`.

`ci_config.ps1` now defines a bunch of "standard variables" gleaned mainly from the environment. These variables are actually defined as global PS constants to avoid accidentally overwriting them.

Before merging, we should check the standard variable names so that we don't have to change them in the future, and aim for intuitive discoverability.

**Comment by guillermooo** [comment]
@randy3k I think this is failing due to PackageControl.io. I don't think I can trigger a rebuild myself.

**Comment by guillermooo** [comment]
@randy3k Would you consider merging this branch at some point? If so, I would continue working on further changes on my clone.

**Comment by randy3k** [comment]
I am not sure about the idea of encoding the dependencies by bade64. The extra step makes it hard to maintain the script.

**Comment by guillermooo** [comment]
I think I can fix that. That aside, would you accept the remaining changes?

**Comment by randy3k** [comment]
I have no issues of refactoring the script to make it agnostic to appveyor in general. But we do want to make sure we do not overly complicate the setup, e.g., why do we need a seperate file for `ci_config.ps1`?

**Pull request closed without merging**
