### PR TITLE
 factor code into modules and make scripts more CI service agnostic

### PR DESCRIPTION
**Pull request by guillermooo**
@randy3k Let me know if this looks better to you!

### CODE REVIEW

**Comment by guillermooo** [comment]
@randy3k Note that users only have to download one script (`appveyor.ps1` or `ci.ps1`). The code is separated into multiple scripts because they are imported from different places. If we end up with a single main script (`ci.ps1`) we could merge all the code into one file, but I don't think it's really necessary.

**Comment by randy3k** [comment]
Thanks. I’ll take a look tomorrow. Good job.

**Comment by randy3k** [comment]
Thank @guillermooo. I have updated the urls and merged the PR in to master. However, I think that it may be still too early to deprecate `appveyor.yml` as it is still the only Windows service which we are supporting, let's keep it here for a little more time.

**Comment by guillermooo** [comment]
@randy3k No problem. I'm actually using VSTS now too with this script. But I don't think it's free for OSS. I will keep working on these and other PS scripts in UnitTesting and send more PRs.

Thanks!

**Pull request merged**
